id: A43F8AC5C
base_file: f151C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:17:23.509976
  last_modified_at: 2022-06-17 11:17:23.509980
