id: A43F8AC5C
base_file: f0E41.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:17:23.506584
  last_modified_at: 2022-06-17 11:17:23.506596
