id: A43F8AC5C
base_file: f6863.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:17:23.512977
  last_modified_at: 2022-06-17 11:17:23.512980
